### PR TITLE
feat: add component:AppBar example

### PR DESCRIPTION
**Pull request by xyz-fish**

### CODE REVIEW

**Review by qytayh — COMMENTED** [review]
1. use prettier to format code
2. use English instead of chinese

**Comment by xyz-fish** [comment]
> 

changed, big lao

**Review by zhenyuWang — COMMENTED** [review]
You should write the Title using the appType component, which is similar to other components, and  Add Right Slot case should have a click method.

**Comment by xyz-fish** [comment]
> You should write the Title using the appType component, which is similar to other components, and Add Right Slot case should have a click method.

done

**Pull request merged**
